[project]
name = "license-plate-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hermeschen1116", email = "108386417+hermeschen1116@users.noreply.github.com" } 
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
license-plate-recognition = "license_plate_recognition:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "catppuccin-jupyterlab>=0.2.4",
    "jupyter>=1.1.1",
    "python-dotenv>=1.0.1",
    "roboflow>=1.1.48",
]
