[project]
name = "taiwan-license-plate-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
	{ name = "hermeschen1116", email = "108386417+hermeschen1116@users.noreply.github.com" },
]
requires-python = ">=3.12"
dependencies = [
	"opencv-python>=4.10.0.84",
	"torch>=2.4.1",
	"transformers>=4.46.0",
	"ultralytics==8.0.238",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
	"catppuccin-jupyterlab>=0.2.4",
	"commitizen>=3.30.0",
	"datasets>=3.0.2",
	"evaluate>=0.4.3",
	"jupyter>=1.1.1",
	"matplotlib>=3.9.2",
	"nncf>=2.13.0",
	"openvino>=2024.4.0",
	"optimum>=1.23.2",
	"pre-commit>=4.0.1",
	"python-dotenv>=1.0.1",
	"roboflow>=1.1.48",
	"wandb>=0.18.5",
]
